import { StyleSheet } from 'react-native';

type AppLayout = {
  phoneWidth: number;
  phoneHeight: number;
};

export const parentSummaryCardBase = {
  width: '48%',
  minHeight: 108,
  borderWidth: 1,
  borderColor: '#ccc',
  borderRadius: 14,
  paddingHorizontal: 16,
  paddingVertical: 14,
  marginBottom: 10,
  justifyContent: 'flex-start',
  shadowColor: '#000',
  shadowOpacity: 0.05,
  shadowRadius: 6,
  shadowOffset: { width: 0, height: 2 },
  elevation: 1,
} as const;

export const createAppStyles = ({ phoneWidth, phoneHeight: _phoneHeight }: AppLayout) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: '#0E0E0F',
    },
    background: {
      flex: 1,
      width: '100%',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      paddingVertical: 0,
      paddingHorizontal: 0,
      backgroundColor: '#050505',
    },
    phoneShell: {
      flex: 1,
      width: '100%',
      height: '100%',
      borderRadius: 0,
      backgroundColor: '#050505',
      padding: 0,
  
    },
    phoneFrame: {
      flex: 1,
      width: '100%',
      height: '100%',
      borderRadius: 0,
      backgroundColor: '#f6f6f7',
      overflow: 'hidden',
      paddingTop: 0,
      paddingHorizontal: 0,
      paddingBottom: 0,
    },
    dashboardTopGradient: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 280,
      zIndex: 0,
    },
    notch: {
      position: 'absolute',
      top: 8,
      alignSelf: 'center',
      width: '30%',
      height: 28,
      borderRadius: 18,
      backgroundColor: '#050505',
      zIndex: 3,
    },
    statusRow: {
      marginTop: 6,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 8,
      marginBottom: 12,
      zIndex: 4,
    },
    timeText: {
      fontSize: 17,
      fontWeight: '700',
      color: '#6B6B6B',
      letterSpacing: 0.2,
    },
    statusIcons: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    statusGlyph: {
      fontSize: 16,
      color: '#2E2E30',
      fontWeight: '800',
    },
    statusGlyphSpacing: {
      marginLeft: 10,
    },
    toolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      position: 'relative',
      marginTop: 0,
      marginBottom: 0,
      paddingTop: 14,
      paddingBottom: 12,
      paddingHorizontal: 12,
      zIndex: 4,
      backgroundColor: 'transparent',
      borderBottomWidth: 0,
    },
    toolbarMenuButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    toolbarBrand: {
      flexDirection: 'row',
      alignItems: 'center',
      flexShrink: 0,
    },
    toolbarBrandLogo: {
      width: 44,
      height: 44,
      marginRight: 8,
    },
    toolbarCenterAbsolute: {
      position: 'absolute',
      left: 0,
      right: 0,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
    },
    toolbarBrandName: {
      fontSize: 18,
      fontWeight: '800',
      color: '#000',
      textAlign: 'center',
      lineHeight: 18,
    },
    toolbarBrandSubtext: {
      fontSize: 11,
      fontWeight: '600',
      color: 'rgba(255,255,255,0.78)',
      textAlign: 'center',
      lineHeight: 14,
    },
    toolbarButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: '#5B308F',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
    },
    toolbarSpacer: {
      flex: 1,
    },
    debugBanner: {
      marginHorizontal: 12,
      marginBottom: 8,
      borderRadius: 10,
      backgroundColor: '#111827',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: '#374151',
    },
    debugBannerText: {
      color: '#E5E7EB',
      fontSize: 11,
      lineHeight: 15,
    },
    debugBannerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 2,
    },
    debugBannerBullet: {
      color: '#93C5FD',
      fontSize: 10,
      fontWeight: '900',
    },
    scrollArea: {
      flex: 1,
    },
    safeArea: {
      flex: 1,
      backgroundColor: '#F6F7FB',
    },
    pageGradient: {
      flex: 1,
    },
    pageTopSpacer: {
      height: 4,
    },
    scrollContent: {
      paddingHorizontal: 4,
      paddingBottom: 120,
      backgroundColor: 'transparent',
    },
    dashboardScrollContent: {
      paddingHorizontal: 4,
      paddingBottom: 120,
    },
    homeSection: {
      marginTop: 2,
    },
    moduleSection: {
      marginTop: 10,
    },
    sectionAnchor: {
      height: 1,
    },
    chipStickyHeader: {
      backgroundColor: '#F6F6F7',
      zIndex: 20,
      paddingTop: 8,
      paddingBottom: 10,
      marginBottom: 8,
      paddingHorizontal: 16,
    },
    chipRowSection: {
      backgroundColor: '#F6F6F7',
      zIndex: 20,
      paddingTop: 8,
      paddingBottom: 6,
      marginBottom: 6,
      paddingHorizontal: 10,
    },
    chipMapRowWrap: {
      paddingHorizontal: 10,
      marginBottom: 8,
    },
    chipRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingLeft: 6,
      paddingRight: 24,
      marginBottom: 0,
    },
    chip: {
      minWidth: 104,
      height: 40,
      paddingHorizontal: 14,
      borderRadius: 20,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFFFFF',
    },
    chipSpacing: {
      marginRight: 8,
    },
    chipInactive: {
      borderColor: '#A8A8A8',
    },
    chipActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
      shadowColor: '#000',
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    chipText: {
      fontSize: 13,
      fontWeight: '500',
    },
    chipTextInactive: {
      color: '#3E3E3E',
    },
    chipTextActive: {
      color: '#F8F8F8',
    },
    selectedChipMapRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingRight: 2,
      paddingTop: 2,
      paddingBottom: 4,
    },
    selectedChipMapItem: {
      minWidth: 72,
      minHeight: 58,
      paddingHorizontal: 8,
      paddingTop: 4,
      paddingBottom: 6,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 0,
      flexDirection: 'column',
      backgroundColor: 'transparent',
    },
    selectedChipMapIconWrap: {
      marginBottom: 4,
      alignItems: 'center',
      justifyContent: 'center',
    },
    selectedChipMapItemSpacing: {
      marginRight: 12,
    },
    selectedChipMapItemInactive: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
    },
    selectedChipMapItemActive: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
    },
    selectedChipMapText: {
      fontSize: 10,
      fontWeight: '700',
      textAlign: 'center',
      lineHeight: 12,
      marginTop: 1,
    },
    selectedChipMapTextInactive: {
      color: '#6A6A70',
    },
    selectedChipMapTextActive: {
      color: '#1F1F22',
      fontWeight: '900',
    },
    selectedChipMapActiveIndicator: {
      marginTop: 6,
      width: 30,
      height: 3,
      borderRadius: 999,
      backgroundColor: '#1F1F22',
    },
    parentActionSection: {
      marginTop: 30,
      marginBottom: 10,
    },
    parentActionTitle: {
      fontSize: 16,
      lineHeight: 20,
      fontWeight: '900',
      color: '#111111',
      marginBottom: 10,
      paddingHorizontal: 14,
    },
    parentActionScroll: {
      paddingHorizontal: 14,
      paddingBottom: 4,
    },
    parentActionCard: {
      width: phoneWidth - 28,
      minHeight: 118,
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingTop: 14,
      paddingBottom: 12,
      marginRight: 10,
      shadowColor: '#000',
      shadowOpacity: 0.12,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
      overflow: 'hidden',
      color:'#000'
    },
    parentActionCardSpacing: {
      marginRight: 14,
    },
    parentActionCardBody: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      flex: 1,
      gap: 10,
    },
    parentActionCardTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    parentActionCardLabel: {
      fontSize: 11,
      lineHeight: 13,
      fontWeight: '800',
      color: '#000',
      textTransform: 'uppercase',
      letterSpacing: 0.3,
      marginBottom: 3,
    },
    parentActionCardValue: {
      fontSize: 18,
      lineHeight: 22,
      fontWeight: '900',
      color: '#000',
      marginBottom: 4,
    },
    parentActionCardSubtitle: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '600',
      color: 'rgba(0,0,0,0.88)',
      marginBottom: 10,
    },
    parentActionCta: {
      alignSelf: 'flex-start',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: 'rgba(255,255,255,0.18)',
    },
    parentActionCtaText: {
      fontSize: 11,
      lineHeight: 12,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    parentActionImage: {
      width: 82,
      height: 82,
      marginLeft: 4,
      alignSelf: 'center',
    },
    dashboardIntro: {
      paddingHorizontal: 16,
      paddingTop: 18,
      paddingBottom: 8,
      alignItems: 'center',
    },
    dashboardTitle: {
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '700',
      color: '#2B2B65',
      textAlign: 'center',
      marginBottom: 10,
    },
    dashboardIntroText: {
      fontSize: 15,
      lineHeight: 20,
      color: '#2E2E2E',
      textAlign: 'center',
      paddingHorizontal: 12,
    },
    dashboardHeroCard: {
      marginHorizontal: 14,
      marginTop: 12,
      borderRadius: 14,
      backgroundColor: 'transparent',
      paddingHorizontal: 0,
      paddingTop: 0,
      paddingBottom: 0,
      height: 220,
      shadowColor: '#1E2A6E',
      shadowOpacity: 0.18,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
      overflow: 'visible',
      
    },
    dashboardHeroSticky: {
      zIndex: 20,
      elevation: 6,
    },
    dashboardHeroGradientCard: {
      position: 'relative',
      flex: 1,
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingTop: 0,
      paddingBottom: 10,
      minHeight: 190,
      overflow: 'visible',
    },
    dashboardHeroCardCollapsed: {
      minHeight: 110,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 14,
    },
    dashboardHeroExpandedAvatarWrap: {
      width: 92,
      height: 92,
      borderRadius: 46,
      borderWidth: 3,
      borderColor: '#0a3d62',
      overflow: 'hidden',
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    dashboardHeroExpandedLayout: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      minHeight: 150,
      paddingTop: 0,
    },
    dashboardHeroExpandedLeft: {
      flex: 1,
      paddingTop: 10,
      paddingRight: 12,
      justifyContent: 'center',
    },
    dashboardHeroExpandedRight: {
      position: 'absolute',
      top: 0,
      right: 12,
      width: 118,
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      paddingTop: 0,
      paddingBottom: 0,
      zIndex: 6,
    },
    dashboardHeroActiveProfileFloat: {
      position: 'absolute',
      top: -30,
      right: 16,
      zIndex: 20,
    },
    dashboardHeroProfilesRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'flex-end',
      gap: 6,
      flexShrink: 0,
    },
    dashboardHeroProfileItem: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    dashboardHeroPrimaryProfile: {
      width: 58,
      height: 58,
      borderRadius: 29,
      borderWidth: 3,
      borderColor: '#0a3d62',
      backgroundColor: '#FFFFFF',
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 10,
    },
    dashboardHeroPrimaryAvatar: {
      width: '100%',
      height: '100%',
    },
    dashboardHeroPrimaryAvatarText: {
      width: '100%',
      height: '100%',
      textAlign: 'center',
      textAlignVertical: 'center',
      fontSize: 24,
      lineHeight: 58,
      fontWeight: '900',
      color: '#FFFFFF',
      backgroundColor: '#4B73E6',
    },
    dashboardHeroSecondaryProfile: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1.5,
      borderColor: '#FFFFFF',
      backgroundColor: '#DDE7F8',
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 0,
    },
    dashboardHeroSecondaryAvatarWrap: {
      width: 34,
      height: 34,
      borderRadius: 17,
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#DDE7F8',
    },
    dashboardHeroSecondaryAvatar: {
      width: '100%',
      height: '100%',
    },
    dashboardHeroSecondaryAvatarText: {
      width: '100%',
      height: '100%',
      textAlign: 'center',
      textAlignVertical: 'center',
      fontSize: 11,
      lineHeight: 34,
      fontWeight: '900',
      color: '#FFFFFF',
      backgroundColor: '#4B73E6',
    },
    dashboardHeroChildName: {
      display: 'none',
      fontSize: 9.5,
      lineHeight: 11,
      fontWeight: '800',
      color: '#FFFFFF',
      textAlign: 'center',
      marginBottom: 0,
    },
    dashboardHeroChildMeta: {
      fontSize: 9.5,
      lineHeight: 11,
      fontWeight: '600',
      color: 'rgba(255,255,255,0.8)',
      textAlign: 'center',
    },
    dashboardHeroChildrenEmpty: {
      color: 'rgba(255,255,255,0.8)',
      fontSize: 11,
      fontStyle: 'italic',
    },
    dashboardHeroAvatarWrap: {
      width: 68,
      height: 68,
      borderRadius: 34,
      borderWidth: 3,
      borderColor: '#0a3d62',
      overflow: 'hidden',
      backgroundColor: '#FFFFFF',
      zIndex: 5,
    },
    dashboardHeroAvatar: {
      width: '100%',
      height: '100%',
    },
    dashboardHeroAvatarText: {
      width: '100%',
      height: '100%',
      textAlign: 'center',
      textAlignVertical: 'center',
      fontSize: 26,
      fontWeight: '900',
      color: '#FFFFFF',
      backgroundColor: '#4B73E6',
      lineHeight: 70,
    },
    dashboardHeroExpandedAvatarText: {
      width: '100%',
      height: '100%',
      textAlign: 'center',
      textAlignVertical: 'center',
      fontSize: 34,
      fontWeight: '900',
      color: '#FFFFFF',
      backgroundColor: '#4B73E6',
      lineHeight: 92,
    },
    dashboardHeroCollapsedContent: {
      minHeight: 78,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      paddingVertical: 4,
    },
    dashboardHeroCollapsedAvatarWrap: {
      width: 54,
      height: 54,
      borderRadius: 27,
      borderWidth: 3,
      borderColor: '#0a3d62',
      overflow: 'hidden',
      backgroundColor: '#FFFFFF',
      marginRight: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dashboardHeroCollapsedAvatar: {
      width: '100%',
      height: '100%',
    },
    dashboardHeroCollapsedName: {
      textAlign: 'left',
      fontSize: 18,
      lineHeight: 22,
      marginBottom: 0,
    },
    dashboardHeroTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: 16,
      paddingLeft: 0,
    },
    dashboardHeroSchool: {
      fontSize: 12.5,
      lineHeight: 14,
      fontWeight: '800',
      color: 'rgba(255,255,255,0.92)',
      marginRight: 8,
      marginBottom: 4,
    },
    dashboardHeroLogout: {
      backgroundColor: '#E94B4B',
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 6,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dashboardHeroLogoutText: {
      fontSize: 11,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    dashboardHeroBody: {
      paddingLeft: 0,
      paddingTop: 2,
    },
    dashboardHeroName: {
      fontSize: 22,
      lineHeight: 26,
      fontWeight: '800',
      color: '#FFFFFF',
      marginBottom: 0,
      marginTop: 0,
      textAlign: 'left',
    },
    dashboardHeroClass: {
      fontSize: 16,
      lineHeight: 20,
      fontWeight: '700',
      color: '#EAF0FF',
      marginBottom: 4,
      marginTop: 0,
      textAlign: 'left',
    },
    dashboardHeroDetails: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      paddingBottom: 2,
    },
    dashboardHeroDetailItem: {
      minWidth: '31%',
      flexGrow: 1,
      borderRadius: 12,
      backgroundColor: 'rgba(255,255,255,0.14)',
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    dashboardHeroDetailLabel: {
      fontSize: 10,
      lineHeight: 12,
      fontWeight: '800',
      color: 'rgba(255,255,255,0.78)',
      textTransform: 'uppercase',
      letterSpacing: 0.3,
      marginBottom: 2,
    },
    dashboardHeroDetailValue: {
      fontSize: 12.5,
      lineHeight: 16,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    dashboardHeroStats: {
      flexDirection: 'row',
      gap: 14,
    },
    dashboardStatBlock: {
      flex: 1,
    },
    dashboardStatHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 6,
    },
    dashboardStatLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: '#FFFFFF',
    },
    dashboardStatValue: {
      fontSize: 13,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    dashboardStatTrack: {
      width: '100%',
      height: 4,
      borderRadius: 999,
      backgroundColor: 'rgba(255,255,255,0.35)',
      overflow: 'hidden',
    },
    dashboardStatFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: '#F2D84A',
    },
    dashboardStatFooter: {
      marginTop: 6,
      fontSize: 10.5,
      lineHeight: 12,
      color: 'rgba(255,255,255,0.88)',
      fontWeight: '600',
    },
    dashboardSectionHeader: {
      marginTop: 22,
      marginBottom: 12,
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    dashboardSectionTitle: {
      fontSize: 19,
      lineHeight: 24,
      fontWeight: '700',
      color: '#7E8A9A',
    },
    dashboardSectionAction: {
      fontSize: 12,
      fontWeight: '600',
      color: '#4B73E6',
    },
    academicGraphSection: {
      marginTop: 14,
      marginHorizontal: 10,
      borderRadius: 22,
      backgroundColor: '#E9F1FF',
      padding: 14,
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 5 },
      elevation: 2,
    },
    academicGraphSectionInner: {
      borderRadius: 18,
      overflow: 'hidden',
      backgroundColor: 'rgba(255,255,255,0.32)',
      padding: 0,
    },
    academicGraphHeader: {
      paddingHorizontal: 2,
      paddingTop: 2,
      paddingBottom: 8,
    },
    academicGraphHeaderText: {
      gap: 2,
    },
    academicGraphTitle: {
      fontSize: 18,
      lineHeight: 22,
      fontWeight: '800',
      color: '#111827',
    },
    academicGraphSubtitle: {
      fontSize: 12.5,
      lineHeight: 18,
      color: '#4B5563',
    },
    academicGraphLegendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingHorizontal: 2,
      paddingBottom: 10,
      flexWrap: 'wrap',
    },
    academicGraphLegendItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    academicGraphLegendDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
    },
    academicGraphLegendText: {
      fontSize: 12.5,
      lineHeight: 16,
      fontWeight: '700',
      color: '#1F2937',
    },
    academicGraphCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: '#EEF0F4',
      paddingVertical: 8,
      paddingHorizontal: 6,
      alignItems: 'center',
      justifyContent: 'center',
    },
    academicGraphEmptyState: {
      paddingVertical: 56,
      paddingHorizontal: 16,
      textAlign: 'center',
      color: '#6B7280',
      fontSize: 13,
      lineHeight: 18,
    },
    dashboardAnnouncementRow: {
      paddingHorizontal: 14,
      paddingBottom: 2,
      gap: 10,
    },
    dashboardAnnouncementCard: {
      width: 140,
      borderRadius: 16,
      padding: 12,
      marginRight: 8,
      minHeight: 132,
      shadowColor: '#000',
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    },
    dashboardAnnouncementThumb: {
      width: 46,
      height: 46,
      borderRadius: 12,
      backgroundColor: 'rgba(255,255,255,0.16)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    dashboardAnnouncementTitle: {
      fontSize: 13,
      lineHeight: 16,
      fontWeight: '700',
      color: '#FFFFFF',
      marginBottom: 6,
    },
    dashboardAnnouncementSubtitle: {
      fontSize: 11,
      lineHeight: 14,
      color: 'rgba(255,255,255,0.82)',
      marginBottom: 10,
    },
    dashboardAnnouncementDate: {
      fontSize: 10,
      lineHeight: 12,
      color: 'rgba(255,255,255,0.75)',
    },
    dashboardTileGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      paddingHorizontal: 14,
      gap: 10,
      marginBottom: 18,
    },
    dashboardTileCard: {
      width: Math.floor((phoneWidth - 56) / 3),
      minHeight: 86,
      borderRadius: 10,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E7E7EC',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      paddingHorizontal: 8,
      shadowColor: '#000',
      shadowOpacity: 0.05,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    dashboardTileIconWrap: {
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
    },
    dashboardTileLabel: {
      fontSize: 11,
      lineHeight: 13,
      fontWeight: '600',
      color: '#404040',
      textAlign: 'center',
    },
    studentProfileCard: {
      marginTop: 12,
      marginBottom: 14,
      borderRadius: 28,
      backgroundColor: '#67339D',
      overflow: 'hidden',
      paddingHorizontal: 12,
      paddingTop: 12,
      paddingBottom: 12,
      shadowColor: '#2B124D',
      shadowOpacity: 0.28,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
      borderWidth: 2,
      borderColor: 'rgba(230, 211, 255, 0.34)',
    },
    studentProfileCardCollapsed: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      minHeight: 126,
    },
    studentProfileHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
      zIndex: 2,
    },
    studentProfileHeaderText: {
      flex: 1,
      paddingRight: 8,
    },
    studentProfileSchool: {
      fontSize: 12,
      fontWeight: '900',
      color: '#F5EAFF',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      marginBottom: 1,
    },
    studentProfileTitle: {
      fontSize: 27,
      lineHeight: 30,
      fontWeight: '900',
      color: '#FFFFFF',
      letterSpacing: 0,
      marginBottom: 3,
    },
    studentProfileSubtitle: {
      fontSize: 12,
      lineHeight: 16,
      color: '#EBDFFF',
      maxWidth: 242,
    },
    studentProfileAvatarWrap: {
      width: 102,
      height: 102,
      borderRadius: 18,
      backgroundColor: '#4CCCDD',
      borderWidth: 3,
      borderColor: 'rgba(255,255,255,0.9)',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOpacity: 0.18,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 3,
    },
    studentProfileCurveWrap: {
      width: '100%',
      height: 52,
      marginTop: -10,
      marginBottom: -18,
      zIndex: 1,
    },
    studentProfileAvatar: {
      width: '100%',
      height: '100%',
    },
    studentProfileAvatarText: {
      fontSize: 28,
      fontWeight: '900',
      color: '#FFFFFF',
    },
    studentProfileCollapsedCenter: {
      minHeight: 104,
      alignItems: 'center',
      justifyContent: 'center',
    },
    studentProfileCardBody: {
      marginTop: 0,
      backgroundColor: '#FFFFFF',
      borderRadius: 22,
      paddingTop: 16,
      paddingBottom: 12,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 10,
      zIndex: 0,
    },
    studentProfileInfoColumn: {
      flex: 1,
      gap: 6,
    },
    studentProfileInfoRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
      minHeight: 18,
    },
    studentProfileLabel: {
      flex: 0.9,
      fontSize: 11.5,
      fontWeight: '700',
      color: '#7D748A',
      lineHeight: 15,
    },
    studentProfileValue: {
      flex: 1.1,
      fontSize: 12.5,
      fontWeight: '900',
      color: '#221335',
      lineHeight: 15,
      textAlign: 'right',
    },
    studentProfileAccentRail: {
      width: 6,
      borderRadius: 999,
      backgroundColor: '#7350D6',
    },
    launcherHintCard: {
      marginTop: 14,
      marginHorizontal: 4,
      borderRadius: 18,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E8E8EC',
      paddingHorizontal: 16,
      paddingVertical: 18,
      shadowColor: '#000',
      shadowOpacity: 0.05,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    launcherHintTitle: {
      fontSize: 18,
      fontWeight: '900',
      color: '#141416',
      marginBottom: 6,
    },
    launcherHintText: {
      fontSize: 13,
      lineHeight: 18,
      color: '#66666D',
    },
    moduleHeaderCard: {
      borderRadius: 18,
      backgroundColor: '#f6f6f7',
   
      padding: 14,
      marginBottom: 14,
    
    },
    moduleHeaderTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    moduleHeaderTextBlock: {
      flex: 1,
    },
    moduleHeaderTitle: {
      fontSize: 18,
      fontWeight: '900',
      color: '#131313',
      marginBottom: 4,
    },
    moduleHeaderSubtitle: {
      fontSize: 12,
      lineHeight: 17,
      color: '#5E5E62',
    },
    moduleHeaderBadge: {
      minWidth: 48,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: '#3F3F40',
      alignItems: 'center',
      justifyContent: 'center',
    },
    moduleHeaderBadgeText: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: '800',
    },
    moduleHeaderActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 12,
      gap: 10,
    },
    moduleWorkspace: {
      flexGrow: 1,
      justifyContent: 'center',
      paddingBottom: 8,
    },
    moduleNavButton: {
      flex: 1,
      minHeight: 42,
      borderRadius: 12,
      backgroundColor: '#F1F3F6',
      borderWidth: 1,
      borderColor: '#D9D9DD',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    moduleNavButtonText: {
      fontSize: 12.5,
      fontWeight: '800',
      color: '#2B2B2B',
    },
    enrollmentLeadStrip: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingBottom: 8,
      marginBottom: 10,
      gap: 8,
    },
    leadCard: {
      width: 132,
      borderRadius: 14,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E1E4EA',
      padding: 10,
      marginRight: 8,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: 7,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    leadCardActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    leadCardTitle: {
      fontSize: 12,
      fontWeight: '800',
      color: '#1C1C1C',
      marginBottom: 4,
    },
    leadCardTitleActive: {
      color: '#FFFFFF',
    },
    leadCardMeta: {
      fontSize: 10.5,
      lineHeight: 14,
      color: '#5B5B60',
      marginBottom: 2,
    },
    leadCardMetaActive: {
      color: '#EDEDED',
    },
    communicationToolbar: {
      marginBottom: 8,
    },
    timelineStrip: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingBottom: 8,
      marginBottom: 8,
      gap: 8,
    },
    timelineCard: {
      width: 132,
      borderRadius: 14,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E1E4EA',
      padding: 10,
      marginRight: 8,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: 7,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    timelineCardActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    timelineCardDate: {
      fontSize: 10,
      fontWeight: '800',
      color: '#6A6A70',
      marginBottom: 4,
    },
    timelineCardDateActive: {
      color: '#EDEDED',
    },
    timelineCardName: {
      fontSize: 12,
      fontWeight: '800',
      color: '#1C1C1C',
      marginBottom: 4,
    },
    timelineCardNameActive: {
      color: '#FFFFFF',
    },
    timelineCardMeta: {
      fontSize: 10.5,
      lineHeight: 14,
      color: '#5B5B60',
      marginBottom: 2,
    },
    timelineCardMetaActive: {
      color: '#EDEDED',
    },
    tabStrip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    tabChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: '#F1F3F6',
      borderWidth: 1,
      borderColor: '#D9D9DD',
    },
    tabChipActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    tabChipText: {
      fontSize: 11.5,
      fontWeight: '800',
      color: '#2B2B2B',
    },
    tabChipTextActive: {
      color: '#FFFFFF',
    },
    teacherGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    teacherCard: {
      width: 132,
      borderRadius: 14,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E1E4EA',
      padding: 10,
      marginRight: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    teacherCardActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    teacherCardIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: '#F1F3F6',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
    },
    teacherCardIconText: {
      fontSize: 14,
      fontWeight: '900',
      color: '#2B2B2B',
    },
    teacherCardIconTextActive: {
      color: '#FFFFFF',
    },
    teacherCardName: {
      fontSize: 12,
      fontWeight: '800',
      color: '#1C1C1C',
      marginBottom: 4,
      textAlign: 'center',
    },
    teacherCardNameActive: {
      color: '#FFFFFF',
    },
    teacherCardMeta: {
      fontSize: 10.5,
      lineHeight: 14,
      color: '#5B5B60',
      textAlign: 'center',
    },
    teacherCardMetaActive: {
      color: '#EDEDED',
    },
    reportTable: {
      minWidth: 760,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E1E4EA',
      overflow: 'hidden',
      backgroundColor: '#f6f6f7',
      marginTop: 6,
    },
    reportTableHeader: {
      flexDirection: 'row',
      backgroundColor: '#F1F3F6',
      borderBottomWidth: 1,
      borderBottomColor: '#E1E4EA',
    },
    reportTableHeaderCell: {
      minWidth: 98,
      paddingVertical: 10,
      paddingHorizontal: 10,
      fontSize: 11,
      fontWeight: '800',
      color: '#202020',
    },
    reportTableRow: {
      flexDirection: 'row',
      borderBottomWidth: 1,
      borderBottomColor: '#EEF1F4',
    },
    reportTableCell: {
      minWidth: 98,
      paddingVertical: 10,
      paddingHorizontal: 10,
      fontSize: 11,
      color: '#333333',
    },
    heroCard: {
      height: 196,
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: '#BFC3D4',
      marginBottom: 14,
      position: 'relative',
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 2,
    },
    heroGlow: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(120, 138, 186, 0.16)',
    },
    heroImage: {
      width: '100%',
      height: '100%',
    },
    sectionTitle: {
      fontSize: 17,
      fontWeight: '800',
      color: '#171717',
      marginBottom: 10,
    },
    dashboardStickyHeader: {
      backgroundColor: '#F6F6F7',
      paddingTop: 4,
      paddingBottom: 10,
      marginBottom: 6,
      zIndex: 10,
    },
    grid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-start',
      alignContent: 'flex-start',
      maxHeight: 160,
      overflow: 'hidden',
      marginBottom: 14,
    },
    gridCard: {
      width: '22.5%',
      minHeight: 68,
      borderRadius: 12,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#ECECEC',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      paddingHorizontal: 6,
      marginBottom: 10,
      marginRight: 8,
      shadowColor: '#000',
      shadowOpacity: 0.035,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
      elevation: 1,
    },
    dashboardGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      alignContent: 'flex-start',
      paddingHorizontal: 8,
      marginBottom: 14,
    },
    dashboardGridCard: {
      width: '47.5%',
      minHeight: 156,
      borderRadius: 30,
      backgroundColor: '#FFFFFF',
      borderWidth: 1.25,
      borderColor: '#D9DDE5',
      position: 'relative',
      overflow: 'hidden',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      paddingTop: 0,
      paddingBottom: 0,
      paddingHorizontal: 0,
      marginBottom: 12,
      shadowColor: '#000',
      shadowOpacity: 0.07,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 3,
    },
    dashboardGridCardThree: {
      width: Math.floor((phoneWidth - 48) / 3),
      minHeight: 92,
      borderRadius: 12,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E1E4EA',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      paddingHorizontal: 6,
      marginBottom: 10,
      shadowColor: '#000',
      shadowOpacity: 0.035,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
      elevation: 1,
    },
    dashboardGridScrollArea: {
      marginHorizontal: 0,
      paddingHorizontal: 5,
    },
    dashboardGridScroller: {
      paddingHorizontal: 5,
      marginBottom: 14,
    },
    dashboardGridColumn: {
      flexDirection: 'column',
    },
    dashboardGridColumnSpacing: {
      marginRight: 4,
    },
    dashboardGridCardActive: {
      backgroundColor: '#FFFFFF',
      borderColor: '#D9DDE5',
    },
    dashboardGridCardContent: {
      width: '100%',
      flex: 1,
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'flex-start',
      paddingTop: 0,
    },
    dashboardGridCornerAccent: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: 32,
      height: 86,
      borderBottomRightRadius: 76,
      borderTopLeftRadius: 0,
      opacity: 0.95,
      backgroundColor: '#0a3d62',
    },
    dashboardGridTextBlock: {
      flex: 1,
      minWidth: 0,
      width: '100%',
      alignItems: 'flex-end',
      justifyContent: 'flex-start',
      paddingTop: 58,
      paddingBottom: 10,
      paddingHorizontal: 16,
    },
    gridIconWrap: {
      width: 38,
      height: 38,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'absolute',
      top: 2,
      right: 12,
      backgroundColor: 'transparent',
      marginBottom: 0,
    },
    gridLabel: {
      fontSize: 13.5,
      textAlign: 'center',
      fontWeight: '800',
      color: '#191919',
      lineHeight: 16,
      marginTop: 20,
      marginBottom: 0,
      paddingHorizontal: 4,
    },
    dashboardGridMetaLabel: {
      fontSize: 12.5,
      lineHeight: 15,
      color: '#78787E',
      fontWeight: '700',
      marginBottom: 3,
      textAlign: 'right',
    },
    dashboardGridMetaValue: {
      fontSize: 14.5,
      lineHeight: 17,
      color: '#2F2F31',
      fontWeight: '800',
      textAlign: 'right',
      marginBottom: 0,
    },
    modulePanel: {
      marginTop: 16,
      marginBottom: 16,
      borderRadius: 18,
      backgroundColor: 'transparent',
      borderWidth: 0,
      borderColor: 'transparent',
      paddingTop: 18,
      paddingHorizontal: 0,
      paddingBottom: 14,
      overflow: 'hidden',
      shadowColor: 'transparent',
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffset: { width: 0, height: 0 },
      elevation: 0,
    },
    moduleHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      marginTop: 8,
      marginBottom: 10,
    },
    moduleTitle: {
      flex: 1,
      fontSize: 18,
      fontWeight: '900',
      color: '#131313',
    },
    modulePointsList: {
      gap: 10,
    },
    modulePointRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    modulePointDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginTop: 6,
      backgroundColor: '#3F3F40',
    },
    modulePointText: {
      flex: 1,
      fontSize: 13,
      lineHeight: 19,
      color: '#444',
    },
    registerPanel: {
      marginBottom: 16,
      borderRadius: 16,
      backgroundColor: 'transparent',
      padding: 12,
    },
    leadDetailsSection: {
      marginBottom: 10,
    },
    leadDetailsTitle: {
      fontSize: 16,
      fontWeight: '900',
      color: '#111111',
      marginBottom: 8,
    },
    leadMetaStrip: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 8,
    },
    leadMetaPill: {
      flex: 1,
      borderRadius: 14,
      backgroundColor: '#F7F7F8',
      borderWidth: 1,
      borderColor: '#E4E4E8',
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    leadMetaLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: '#676767',
      marginBottom: 2,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    leadMetaValue: {
      fontSize: 12.5,
      fontWeight: '800',
      color: '#141414',
    },
    leadStatsRow: {
      flexDirection: 'row',
      gap: 8,
    },
    leadStatCard: {
      flex: 1,
      minHeight: 108,
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.06)',
    },
    leadStatCardGreen: {
      backgroundColor: '#D7E7CD',
    },
    leadStatCardYellow: {
      backgroundColor: '#F0EE96',
    },
    leadStatTextBlock: {
      flex: 1,
      paddingRight: 8,
    },
    leadStatNumber: {
      fontSize: 21,
      fontWeight: '900',
      color: '#111111',
      lineHeight: 24,
    },
    leadStatLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: '#222222',
      marginTop: 2,
    },
    leadStatFooter: {
      marginTop: 12,
      fontSize: 11.5,
      color: '#2A2A2A',
    },
    leadStatIconWrap: {
      width: 36,
      alignItems: 'flex-end',
      justifyContent: 'center',
    },
    leadReportCard: {
      width: '100%',
      maxWidth: 340,
      borderRadius: 18,
      backgroundColor: '#FFFFFF',
      padding: 16,
      borderWidth: 1,
      borderColor: '#E5E5EA',
    },
    leadReportRow: {
      borderRadius: 14,
      backgroundColor: '#F7F7F8',
      borderWidth: 1,
      borderColor: '#E4E4E8',
      padding: 12,
      marginBottom: 10,
    },
    leadReportName: {
      fontSize: 13.5,
      fontWeight: '900',
      color: '#111111',
      marginBottom: 4,
    },
    leadReportMeta: {
      fontSize: 11.5,
      color: '#404040',
      lineHeight: 15,
    },
    leadReportActionRow: {
      marginTop: 10,
      alignItems: 'flex-end',
    },
    leadReportActionButton: {
      minWidth: 118,
      borderRadius: 14,
      backgroundColor: '#3F3F40',
      paddingHorizontal: 14,
      paddingVertical: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    leadReportActionButtonText: {
      fontSize: 12.5,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    registerHeader: {
      marginBottom: 8,
    },
    registerTitle: {
      fontSize: 16,
      fontWeight: '900',
      color: '#111111',
      marginBottom: 3,
    },
    registerSubtitle: {
      fontSize: 11,
      color: '#707070',
      lineHeight: 15,
    },
    registerBody: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      alignItems: 'stretch',
    },
    formColumn: {
      flex: 1,
      minWidth: 0,
    },
    cameraColumn: {
      width: '100%',
      flexGrow: 1,
      minWidth: 0,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
     formRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 8,
    },
   inputGroup: {
      flex: 1,
      minWidth: 140,
    },
    fullWidthGroup: {
      minWidth: '100%',
    },
    inputLabel: {
      fontSize: 10.5,
      fontWeight: '800',
      color: '#444444',
      marginBottom: 5,
    },
    textInput: {
      minHeight: 40,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: '#BDBDC2',
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 12,
      paddingVertical: 9,
      color: '#111111',
      fontSize: 12.5,
    },
    datePickerField: {
      width: '100%',
      alignSelf: 'stretch',
      minHeight: 38,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#BDBDC2',
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 12,
      paddingVertical: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    datePickerValue: {
      flex: 1,
      color: '#111111',
      fontSize: 12.5,
    },
    datePickerPlaceholder: {
      color: '#A0A0A0',
    },
    multilineInput: {
      minHeight: 56,
      textAlignVertical: 'top',
    },
    photoUploadCard: {
      flexBasis: '100%',
      minHeight: 176,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#E9E9EA',
      backgroundColor: '#F9FAFC',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 14,
    },
    photoCircle: {
      width: 70,
      height: 70,
      borderRadius: 35,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#3F3F40',
      marginBottom: 10,
    },
    photoPreview: {
      width: 88,
      height: 88,
      borderRadius: 44,
      overflow: 'hidden',
      marginBottom: 10,
      borderWidth: 2,
      borderColor: '#D9D9DD',
      backgroundColor: '#FFFFFF',
    },
    photoPreviewImage: {
      width: '100%',
      height: '100%',
    },
    photoCircleText: {
      color: '#FFFFFF',
      fontSize: 30,
      fontWeight: '300',
      lineHeight: 32,
    },
    photoLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: '#202020',
    },
    photoHint: {
      marginTop: 4,
      fontSize: 11,
      color: '#6B6B6B',
      textAlign: 'center',
    },
    registerSummaryCard: {
      flexBasis: '100%',
      borderRadius: 14,
      backgroundColor: '#F7F7F8',
      padding: 11,
      borderWidth: 1,
      borderColor: '#E2E2E6',
    },
    summaryTitle: {
      fontSize: 12.5,
      fontWeight: '900',
      color: '#131313',
      marginBottom: 7,
    },
    summaryText: {
      fontSize: 11,
      lineHeight: 15,
      color: '#404040',
      marginBottom: 2,
    },
    pillRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingBottom: 8,
      marginBottom: 4,
      gap: 8,
    },
    pill: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: '#F1F3F6',
      borderWidth: 1,
      borderColor: '#E0E4EA',
      marginRight: 8,
    },
    pillActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    counsellingToggle: {
      alignSelf: 'flex-start',
      marginTop: 4,
    },
    pillText: {
      fontSize: 11.5,
      fontWeight: '700',
      color: '#2C2C2C',
    },
    pillTextActive: {
      color: '#FFFFFF',
    },
    registerActions: {
      width: '100%',
      marginTop: 2,
      alignItems: 'flex-start',
    },
    enrollmentDocsSection: {
      flexBasis: '100%',
      borderRadius: 16,
      backgroundColor: '#F8FAFD',
      padding: 12,
      borderWidth: 1,
      borderColor: '#E4E8F0',
      marginBottom: 4,
    },
    enrollmentDocsTitle: {
      fontSize: 13,
      fontWeight: '800',
      color: '#131313',
      marginBottom: 10,
    },
    enrollmentDocsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 8,
    },
    enrollmentDocButton: {
      width: '48%',
      minHeight: 58,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#D9D9DD',
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 10,
      paddingVertical: 8,
      justifyContent: 'center',
    },
    enrollmentDocButtonLabel: {
      fontSize: 11.5,
      fontWeight: '800',
      color: '#202020',
      marginBottom: 2,
    },
    enrollmentDocButtonHint: {
      fontSize: 10.5,
      color: '#6B6B6B',
      lineHeight: 14,
    },
    registerButton: {
      minWidth: 150,
      width: '100%',
      paddingHorizontal: 16,
      paddingVertical: 11,
      borderRadius: 12,
      backgroundColor: '#3F3F40',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    registerButtonDisabled: {
      opacity: 0.7,
    },
    registerButtonText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '800',
      letterSpacing: 0.2,
    },
    overlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(10, 10, 10, 0.34)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
      zIndex: 50,
    },
    popupCard: {
      width: '100%',
      maxWidth: 320,
      borderRadius: 18,
      backgroundColor: '#FFFFFF',
      padding: 18,
      borderWidth: 1,
      borderColor: '#E7E7EA',
      shadowColor: '#000',
      shadowOpacity: 0.18,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 6,
    },
    popupTitle: {
      fontSize: 16,
      fontWeight: '900',
      color: '#131313',
      marginBottom: 8,
    },
    popupMessage: {
      fontSize: 12.5,
      lineHeight: 18,
      color: '#444444',
      marginBottom: 14,
    },
    popupActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 10,
    },
    popupButton: {
      minWidth: 90,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    popupButtonPrimary: {
      backgroundColor: '#3F3F40',
    },
    popupButtonSecondary: {
      backgroundColor: '#F1F3F6',
      borderWidth: 1,
      borderColor: '#D9D9DD',
    },
    popupButtonText: {
      fontSize: 12.5,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    popupButtonTextSecondary: {
      color: '#2B2B2B',
    },
    teacherPopupCard: {
      width: '100%',
      maxWidth: 350,
      borderRadius: 18,
      backgroundColor: '#FFFFFF',
      padding: 18,
      borderWidth: 1,
      borderColor: '#E7E7EA',
      shadowColor: '#000',
      shadowOpacity: 0.18,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 6,
    },
    teacherHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    teacherAvatar: {
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#3F3F40',
      marginRight: 12,
    },
    teacherAvatarText: {
      color: '#FFFFFF',
      fontSize: 20,
      fontWeight: '900',
    },
    teacherHeaderText: {
      flex: 1,
    },
    teacherTitle: {
      fontSize: 18,
      fontWeight: '900',
      color: '#131313',
      marginBottom: 4,
    },
    teacherSubtitle: {
      fontSize: 12.5,
      color: '#5E5E62',
      lineHeight: 17,
    },
    teacherDetailsList: {
      marginBottom: 14,
    },
    parentChildrenStrip: {
      paddingTop: 10,
      paddingBottom: 2,
      paddingRight: 4,
    },
    parentChildCard: {
      alignItems: 'center',
      justifyContent: 'flex-start',
      borderRadius: 16,
      paddingTop: 10,
      paddingBottom: 8,
      paddingHorizontal: 10,
      marginRight: 10,
      borderWidth: 1,
      backgroundColor: '#F7F8FA',
      borderColor: '#ECEEF3',
    },
    parentChildCardActive: {
      width: 126,
      backgroundColor: '#EEF4FF',
      borderColor: '#B7C9FF',
      shadowColor: '#0A3D62',
      shadowOpacity: 0.12,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    parentChildCardInactive: {
      width: 92,
      opacity: 0.9,
    },
    parentChildAvatarWrap: {
      borderRadius: 999,
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
      backgroundColor: '#DDE7F8',
      borderWidth: 2,
      borderColor: '#FFFFFF',
    },
    parentChildAvatarWrapActive: {
      width: 78,
      height: 78,
    },
    parentChildAvatarWrapInactive: {
      width: 52,
      height: 52,
    },
    parentChildAvatar: {
      width: '100%',
      height: '100%',
    },
    parentChildAvatarText: {
      textAlign: 'center',
      textAlignVertical: 'center',
      fontWeight: '900',
      color: '#FFFFFF',
      backgroundColor: '#4B73E6',
    },
    parentChildAvatarTextActive: {
      width: 78,
      height: 78,
      lineHeight: 78,
      fontSize: 28,
    },
    parentChildAvatarTextInactive: {
      width: 52,
      height: 52,
      lineHeight: 52,
      fontSize: 18,
    },
    parentChildName: {
      fontSize: 11.5,
      lineHeight: 14,
      fontWeight: '800',
      color: '#1F1F22',
      textAlign: 'center',
      marginBottom: 2,
    },
    parentChildMeta: {
      fontSize: 10,
      lineHeight: 13,
      fontWeight: '600',
      color: '#6A6A70',
      textAlign: 'center',
    },
    teacherDetailRow: {
      marginBottom: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 12,
      backgroundColor: '#F7F8FA',
      borderWidth: 1,
      borderColor: '#ECEEF3',
    },
    teacherDetailLabel: {
      fontSize: 10.5,
      fontWeight: '800',
      color: '#6A6A70',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 4,
    },
    teacherDetailValue: {
      fontSize: 13.5,
      fontWeight: '700',
      color: '#1F1F22',
      lineHeight: 18,
    },
    teacherActions: {
      flexDirection: 'row',
      gap: 10,
    },
    teacherActionButton: {
      flex: 1,
      minWidth: 0,
    },
    teacherLogoutButton: {
      marginTop: 10,
      backgroundColor: '#C63D4D',
    },
    teacherLogoutText: {
      color: '#FFFFFF',
      fontSize: 12.5,
      fontWeight: '800',
    },
    statusCardsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 18,
    },
    statusCard: {
      flex: 1,
      height: 128,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOpacity: 0.06,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    statusCardLeft: {
      marginRight: 8,
    },
    statusCardRight: {
      marginLeft: 8,
    },
    reportCardRow: {
      paddingBottom: 8,
      marginBottom: 6,
      gap: 8,
    },
    reportMiniCard: {
      width: 120,
      minHeight: 112,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E1E4EA',
      backgroundColor: '#FFFFFF',
      padding: 10,
      marginRight: 8,
      justifyContent: 'space-between',
      shadowColor: '#000',
      shadowOpacity: 0.05,
      shadowRadius: 7,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    reportMiniCardActive: {
      backgroundColor: '#3F3F40',
      borderColor: '#3F3F40',
    },
    reportMiniIconWrap: {
      width: 28,
      height: 28,
      marginBottom: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    reportMiniTitle: {
      fontSize: 11,
      fontWeight: '800',
      color: '#1E1E1E',
      marginBottom: 2,
    },
    reportMiniTitleActive: {
      color: '#FFFFFF',
    },
    reportMiniSubtitle: {
      fontSize: 10,
      lineHeight: 14,
      color: '#5D5D61',
    },
    reportMiniSubtitleActive: {
      color: '#F7F7F7',
    },
    reportList: {
      marginTop: 6,
      gap: 10,
    },
    reportRowCard: {
      borderRadius: 14,
      backgroundColor: '#F8FAFD',
      borderWidth: 1,
      borderColor: '#E4E8F0',
      padding: 12,
    },
    reportRowTitle: {
      fontSize: 13,
      fontWeight: '800',
      color: '#131313',
      marginBottom: 4,
    },
    reportRowMeta: {
      fontSize: 11,
      color: '#454545',
      lineHeight: 16,
      marginBottom: 2,
    },
    statusCardText: {
      flex: 1,
      paddingRight: 8,
    },
    statusCardTextScroll: {
      flex: 1,
    },
    statusCardTextScrollContent: {
      paddingRight: 8,
      paddingBottom: 6,
    },
    statusTitleRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      flexWrap: 'wrap',
    },
    statusNumber: {
      fontSize: 18,
      fontWeight: '900',
      color: '#111111',
      marginRight: 4,
    },
    statusSubtitle: {
      fontSize: 12.5,
      fontWeight: '500',
      color: '#252525',
      lineHeight: 18,
    },
    statusFooter: {
      marginTop: 20,
      fontSize: 12.5,
      fontWeight: '500',
      color: '#2B2B2B',
    },
    statusActionButton: {
      marginTop: 6,
      alignSelf: 'flex-start',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#D8D8DC',
    },
    statusActionLink: {
      fontSize: 10.5,
      fontWeight: '800',
      color: '#0A3D62',
    },
    statusIconWrap: {
      width: 34,
      alignItems: 'flex-end',
      justifyContent: 'center',
      paddingTop: 2,
    },
    campaignSummaryCard: {
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E1E4EA',
      paddingHorizontal: 14,
      paddingTop: 14,
      paddingBottom: 12,
      marginBottom: 14,
      shadowColor: '#000',
      shadowOpacity: 0.05,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    campaignSummaryRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
    },
    campaignSummaryItem: {
      flex: 1,
      paddingRight: 10,
      borderRightWidth: 1,
      borderRightColor: '#ECEEF2',
      minHeight: 84,
      justifyContent: 'space-between',
    },
    campaignSummaryItemTotal: {
      borderRightWidth: 0,
      paddingRight: 0,
      paddingLeft: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    campaignSummaryValue: {
      fontSize: 22,
      fontWeight: '900',
      color: '#111111',
      lineHeight: 24,
    },
    campaignSummaryTotalValue: {
      fontSize: 24,
      fontWeight: '900',
      color: '#111111',
      lineHeight: 26,
      marginTop: 2,
      marginBottom: 2,
    },
    campaignSummaryTotalLabel: {
      fontSize: 12,
      fontWeight: '800',
      color: '#1D1D1F',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    campaignSummaryMini: {
      fontSize: 10.5,
      fontWeight: '600',
      color: '#5B5B61',
      marginTop: 2,
    },
    campaignSummaryLabel: {
      fontSize: 11.5,
      fontWeight: '700',
      color: '#2A2A2E',
      lineHeight: 15,
      marginTop: 4,
    },
    campaignSummaryDate: {
      marginTop: 10,
      fontSize: 11,
      color: '#75757B',
      fontWeight: '500',
      textAlign: 'right',
    },
    enrollmentTimelineScroll: {
      maxHeight: 250,
    },
    enrollmentTimelineList: {
      gap: 10,
      paddingBottom: 10,
    },
    enrollmentTimelineItem: {
      borderRadius: 16,
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#E1E4EA',
      paddingVertical: 12,
      paddingHorizontal: 12,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: 7,
      shadowOffset: { width: 0, height: 4 },
      elevation: 1,
    },
    enrollmentTimelineItemActive: {
      backgroundColor: '#F3F5F8',
      borderColor: '#3F3F40',
    },
    enrollmentTimelineConnector: {
      position: 'absolute',
      left: 28,
      top: 56,
      bottom: -10,
      width: 1,
      backgroundColor: '#D7DCE3',
    },
    enrollmentTimelineRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    enrollmentTimelineDate: {
      width: 74,
      paddingRight: 8,
    },
    enrollmentTimelineDateText: {
      fontSize: 10.5,
      fontWeight: '800',
      color: '#4A4A4F',
      marginBottom: 2,
    },
    enrollmentTimelineTimeText: {
      fontSize: 10,
      color: '#6A6A70',
    },
    enrollmentLeadAvatar: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: '#EDF0F4',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
      marginTop: 2,
    },
    enrollmentTimelineDetails: {
      flex: 1,
    },
    enrollmentTimelineStatus: {
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      marginBottom: 8,
    },
    enrollmentStatusRegistered: {
      backgroundColor: '#D9EAD3',
    },
    enrollmentStatusCancelled: {
      backgroundColor: '#F4D7DA',
    },
    enrollmentTimelineStatusText: {
      fontSize: 10,
      fontWeight: '900',
      color: '#323236',
      letterSpacing: 0.4,
    },
    enrollmentTimelineName: {
      fontSize: 12.5,
      fontWeight: '800',
      color: '#1D1D1F',
      marginBottom: 4,
    },
    enrollmentTimelineMeta: {
      fontSize: 11,
      color: '#4C4C52',
      lineHeight: 16,
    },
    enrollmentTimelineMetaBold: {
      fontWeight: '800',
      color: '#1F1F22',
    },
    footer: {
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'flex-end',
      paddingTop: 0,
      paddingBottom: 0,
      paddingHorizontal: 8,
      backgroundColor: '#f6f6f7',
      borderTopWidth: 1,
      borderTopColor: '#ECECF0',
    },
    footerNav: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      marginBottom: 0,
      paddingHorizontal: 2,
    },
    footerNavItem: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 34,
    },
    footerNavLabel: {
      marginTop: 0,
      fontSize: 7,
      color: '#111111',
      fontWeight: '700',
    },
    footerNavLabelMuted: {
      marginTop: 0,
      fontSize: 7,
      color: '#B0B0B5',
      fontWeight: '700',
    },
    footerAddButton: {
      width: 42,
      height: 24,
      borderRadius: 12,
      backgroundColor: '#F14A40',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#E53D33',
      marginBottom: 1,
      shadowColor: '#000',
      shadowOpacity: 0.12,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    poweredBy: {
      fontSize: 7.5,
      color: '#8A8A8A',
      fontWeight: '500',
      marginRight: 4,
    },
    logo: {
      width: 42,
      height: 26,
    },
    footerBrandRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 0,
      marginBottom: 0,
    },   
    homeIndicator: {
      alignSelf: 'center',
      width: 78,
      height: 2,
      borderRadius: 999,
      backgroundColor: '#f13232ff',
      marginTop: -1,
      marginBottom: 0,
    },
  });
